In [14]:
import tensorflow as tf

In [3]:
a= tf.constant(1, dtype=tf.float32)
b= tf.constant([1], dtype=tf.float32)
c= tf.constant([[1,2]], dtype=tf.float32)
d=a*b+c
print(d)



Tensor("add:0", shape=(1, 2), dtype=float32)


### 텐서플로우의 특징: 갈아끼울수 있다.

In [5]:
import tensorflow as tf

input_data=[1,2,3,4,5]
x=tf.placeholder(dtype=tf.float32)
y=x*2

print("x :", x)
print("y :", y)

session=tf.Session()
result=session.run(y, feed_dict={x:input_data})
print(result)

session.close()

x : Tensor("Placeholder_1:0", dtype=float32)
y : Tensor("mul_3:0", dtype=float32)
[ 2.  4.  6.  8. 10.]


*변수

In [8]:
x=tf.placeholder(dtype=tf.float32)
x_data=[1,2,4]

weights=tf.Variable([3], dtype=tf.float32)
biases=tf.Variable([4], dtype=tf.float32)

y=weights*x+biases

print("x : ",x)
print("weights:",weights)
print("biases",biases)

x :  Tensor("Placeholder_4:0", dtype=float32)
weights: <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
biases <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>


In [10]:
with tf.Session() as session:
    #초기화 오퍼레이션
    session.run([weights.initializer, biases.initializer])
    
    result= session.run(y,feed_dict={x:x_data})
    print(result)
    #변수 변경//재할당
    session.run(tf.assign(weights,[2]))
    
    result=session.run(y,feed_dict={x:x_data})
    print(result)

[ 7. 10. 16.]
[ 6.  8. 12.]


In [13]:
init_op=tf.global_variables_initializer()

with tf.Session() as session:
    #초기화 오퍼레이션 불러오시
    session.run(init_op)
    
    result=session.run(y, feed_dict={x:x_data})
    print(result)
    #변수 변경//재할당
    session.run(tf.assign(weights,[1]))
    
    result=session.run(y,feed_dict={x:x_data})
    print(result)
    
    
    

[ 7. 10. 16.]
[5. 6. 8.]
